version: '3'

services:
  crawler:
    image: windyakin/kosen-website-crawler:latest
    build: .
    environment:
      - TZ=Asia/Tokyo
      - S3
      - AWS_S3_BUCKET_REGION
      - AWS_S3_BUCKET_NAME
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
    shm_size: 1g
