version: '3'

services:
  crawler:
    image: kosen_website_crawler
    build: .
    volumes:
      # NOTE: macOS の /etc/localtime はマウントしてもタイムゾーンを変更できない
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=Asia/Tokyo
    shm_size: 256m
