name: ci

on:
  pull_request:

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platforms:
          - linux/amd64
          - linux/arm64
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-qemu-action@v3

      - uses: docker/setup-buildx-action@v2

      - uses: docker/build-push-action@v3
        with:
          platforms: ${{ matrix.platform }}
          tags: windyakin/kosen-website-crawler:latest
          push: false
