name: Build the Docker image test

on:
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Build the Docker image
        run: docker build --pull --no-cache . -f Dockerfile
