name: ci

on:
  pull_request:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: docker/setup-qemu-action@v1

      - uses: docker/setup-buildx-action@v1

      - uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64
          tags: windyakin/kosen-website-crawler:latest
          push: false
